### ISSUE TITLE
Roadmap to full node

### ISSUE THREAD

**Issue by Duddino** [PIVX-Labs/MPW-Tauri#12]
- [ ] Add explorer replaement (#10)
- [ ] Sync the address index
- [ ] Replace jsonrpsee or patch pivxd
- [ ] Fetch sapling params for pivxd and shield
- [ ] Replace node
- [ ] Add syncing UI
